// Code generated by aocgen; DO NOT EDIT.
package year2025

import (
	"testing"

	"aocgen/pkg/aoc"
)

func Benchmark2025Day01(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 1)
	p := aoc.NewPuzzle(2025, 1)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2025Day02(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 2)
	p := aoc.NewPuzzle(2025, 2)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2025Day03(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 3)
	p := aoc.NewPuzzle(2025, 3)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2025Day04(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 4)
	p := aoc.NewPuzzle(2025, 4)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2025Day05(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 5)
	p := aoc.NewPuzzle(2025, 5)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2025Day06(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 6)
	p := aoc.NewPuzzle(2025, 6)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2025Day07(b *testing.B) {
	Init()
	input := aoc.TestInput(2025, 7)
	p := aoc.NewPuzzle(2025, 7)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
